replicaCount: 1
image:
  repository: juanchomc17/devops-app
  pullPolicy: IfNotPresent
  tag: f314b8c78670b2c9e6e70a6f0d08659c7dcb355a
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 5000
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: devops-app.test.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources: {}
livenessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
readinessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
