name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: juanchomc17/devops-app:${{ github.sha }}
    outputs:
      commit_id: ${{ github.sha }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps: 
      - name: Modify values file
        shell: bash
        run: |
          echo ${{needs.ci.outputs.commit_id}}
          pip install yq
          yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/devops-app/values.yaml

      
      - name: Install argocd
        shell: bash
        run: |
          curl -ksSL -o  argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd


      - name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
           --insecure  \
           --grpc-web \
           --username admin \
           --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync devops-app


