name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: juanchomc17/devops-app:${{ github.sha }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps: 

      - name: Argocd app sync
        shell: bash
        run:
          ./argocd login argocd-server.argocd \
           --insecure  \
           --grpc-web \
           --username admin \
           --password ${{ secrets.ARGOCD_PASSWORD }}
          ./argocd app sync devops-app


